- name: restart ferm
  service: name=ferm state=restarted
  notify: restart fail2ban

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart docker
  service: name=docker state=restarted
