---

- name: restart ferm
  service: name=ferm state=restarted
  notify: restart fail2ban

- name: restart ssh
  service: name=ssh state=restarted

- name: restart monit
  service: name=monit state=restarted

- name: update aliases
  command: newaliases

- name: restart fail2ban
  service: name=fail2ban state=restarted
