---

- name: restart ferm
  service: name=ferm state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart monit
  service: name=monit state=restarted

- name: update aliases
  command: newaliases
